spring.application.name=nexcash

# Configurações de conexão com H2
spring.datasource.url=jdbc:h2:mem:nexcashdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ativa o painel do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console